baseurl = "https://lintthew.myvnc.com/"
theme = "cleanwhite"
Language.Locale = "zh-cn"
defaultContentLanguage = "zh-cn"
preserveTaxonomyNames = false
hasCJKLanguage = true
timeZone = "Asia/Shanghai"
enableRobotsTXT = true

[services]
  # Enable comments by entering your Disqus shortname
  [services.disqus]
    #shortname = "matthew-blog-1"
  [services.googleAnalytics]
    id = "G-H7PS1PRVFE"

[pagination]
  pagerSize = 5 # frontpage pagination

[outputs]
home = ["HTML", "RSS", "algolia"]

[languages]
  [languages.zh-cn]
    languageCode = "zh-cn"
    languageName = "中文"
    weight = 1
    title = "林修的博客" 	# 你的中文博客标题
	
	# 🌟 显式告诉 Hugo，中文下的分类和标签路由叫什么
	[languages.zh-cn.taxonomies]
      category = "categories"
      tag = "tags"
	
	[languages.zh-cn.params]
	  #header_image = "img/home-bg-elsa2.png"
	  #slogan = ""
	  SEOTitle = "林修的博客"
	  description = ""
	  keyword = ""
	  image_404 = "img/404-bg.jpg"
	  title_404 = "没有内容可供阅读 :("
	  last_posts_title = "最新文章"
	  # Sidebar settings
	  #sidebar_avatar = "img/avatar-me.png"
	  sidebar_about_description = ""
	  
	  # Enable wechat pay & alipay to allow readers send reward money if they like the articles 
	  reward = true 
	  reward_guide = "如果这篇文章对你有用,请随意打赏" 
    [[languages.zh-cn.params.additional_menus]]
      title = "归档"
      href = "/archive"
	[[languages.zh-cn.params.additional_menus]]
      title = "标签"
      href = "/tags"
    #[[languages.zh-cn.params.additional_menus]]
      #title = "笔记"
      #href = "/notes"
    [[languages.zh-cn.params.additional_menus]]
      title = "关于"
      href = "/about"
	[[languages.zh-cn.params.additional_menus]]
	  title = "留言"
	  href = "/message"
	
  [languages.en]
    languageCode = "en"
    languageName = "English"
    weight = 2
    title = "Matthew Blog" # 你的英文博客标题
	
	# 🌟 显式告诉 Hugo，英文下的分类和标签路由叫什么
	[languages.en.taxonomies]
	  category = "categories"
      tag = "tags"
	
	[languages.en.params]
	  #header_image = "img/home-bg-elsa.png"
	  #slogan = "Be Happy"
	  SEOTitle = "Matthew Lin's Blog"
	  description = ""
	  keyword = ""
	  image_404 = "img/404-bg.jpg"
	  title_404 = "Oops! Page Not Found :("
	  last_posts_title = "LAST POSTS"
	  # Sidebar settings
	  #sidebar_avatar = "img/avatar-me.png"
	  sidebar_about_description = ""
	  
	  # Enable wechat pay & alipay to allow readers send reward money if they like the articles 
	  # 全局的开关-每个文章里也有单独的开关
	  reward = true 
	  reward_guide = "If this article is helpful to you, please feel free to make a donation." 
    [[languages.en.params.additional_menus]]
      title = "ARCHIVE"
      href = "/archive"
	[[languages.en.params.additional_menus]]
      title = "TAGS"
      href = "/tags"
    #[[languages.en.params.additional_menus]]
      #title = "NOTES"
      #href = "/notes"
    [[languages.en.params.additional_menus]]
      title = "ABOUT"
      href = "/about"
	[[languages.en.params.additional_menus]]
	  title = "MESSAGE"
	  href = "/message"
	
[params]
  #header_image = "img/home-bg-elsa2.png"
  #SEOTitle = "Matthew Lin的博客 | Lin Matthew Blog"
  #description = "nothing special about Matthew Lin."
  #keyword = ""
  #slogan = "路在脚下，心向远方"
  upstreamAttribution = true

  #image_404 = "img/404-bg.jpg"
  #title_404 = "你来到了没有知识的荒原 :("
  omit_categories = false

  # leancloud storage for page view counter
  page_view_counter = false
  leancloud_app_id = ""
  leancloud_app_key = ""

  # algolia site search
  algolia_search = false
  algolia_appId = ""
  algolia_indexName = ""
  algolia_apiKey = ""

  # Sidebar settings
  # sidebar_about_description = "Software Developer, Open Source Enthusiast and Life Adventurer"
  # sidebar_avatar = "img/avatar-me.png"      # use absolute URL, seeing it's used in both `/` and `/about/`

  featured_tags = true 
  featured_condition_size = 1 

  # Baidu Analytics
  ba_track_id = ""
  
  # 🌟 填入你部署成功的 Vercel 网址
  #waline_server = "https://waline-comment-pearl-six.vercel.app"
  waline_server = "https://waline.myvnc.com"
  
  # We need a proxy to access Disqus api in China
  # Follow https://github.com/zhaohuabing/disqus-php-api to set up your own disqus proxy
  #disqus_proxy = ""
  #disqus_site = ""

  # Twikoo comments
  # Follow https://twikoo.js.org/ to set up your own env_id
  #twikoo_env_id = ""

  # Artalk comments
  # Follow https://artalk.js.org/ to set up your own server
  #artalk_enable = true
  #artalk_server = "https://xxx.xxx.com"
  #artalk_site = "xxx blog"

  #Enable wechat pay & alipay to allow readers send reward money if they like the articles 
  #reward = false 
  # reward_guide = "如果这篇文章对你有用,请随意打赏" 

  friends = true
  bookmarks = false
  about_me = true

  # Last posts
  last_posts = true
  #last_posts_title = "LAST POSTS"
  #last_posts_count = 5

  # Include any custom CSS and/or JS files, url or relative to /static folder
  #custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css",  "css/main.css", "css/custom.css"]
  #custom_js = ["js/lightbox.js", "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/main.js", "js/custom.js"]
  custom_css = ["css/lightbox.css", "https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.7.2/animate.min.css", "css/custom.css"]
  custom_js = ["https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js", "js/lightbox.js", "js/custom.js"]

  [params.social]
  rss            = true 
  email          = "dawndusk@outlook.com"
  #facebook      = "full profile url in facebook"
  #googleplus    = "full profile url in googleplus"
  #twitter       = "full profile url in twitter"
  #linkedin       = "https://www.linkedin.com/in/yourlinkedinid"
  #stackoverflow  = "https://stackoverflow.com/users/yourstackoverflowid"
  #instagram     = "full profile url in instagram"
  github         = "https://github.com/Lin-Matthew"
  wechat         = "your wechat qr code image"
  #wechat         = "/img/wechat_qrcode.png"
  #medium        = "full profile url in medium"
  #slack         = "full workspace url in slack"
  #pinterest     = "full profile url in pinterest"
  #reddit        = "full profile url in reddit"
  #gitlab        = "full profile url in gitlab"
  #mastodon      = "full profile url in mastodon"
  #keybase       = "full profile url in keybase"
  #xing          = "https://www.xing.com/profile/yourxingid"
  #git           = "full profile url for git user"
  
  [[params.friend_link]]
  #title = "Linda的博客"
  #href =  "https://zhaozhihan.com"

  [[params.bookmark_link]]
  title =  "Martin Fowler"
  href =  "https://martinfowler.com"
  [[params.bookmark_link]]
  title = "ServiceMesher"
  href =  "http://www.servicemesher.com"
  [[params.bookmark_link]]
  title =  "Pxhere"
  href = "https://pxhere.com"
  [[params.bookmark_link]]
  title = "unsplash"
  href = "https://unsplash.com"


[outputFormats.Algolia]
baseName = "algoliSearch"
isPlainText = true
mediaType = "application/json"
notAlternative = true

[params.algolia]
vars = ["title", "summary", "date", "publishdate", "expirydate", "permalink"]
params = ["categories", "tags"] 

[markup]
  [markup.tableOfContents]
    endLevel = 3
    startLevel = 1
  [markup.highlight]
	codeFences = true
    guessSyntax = true
    lineNos = false # 如果不需要行号可以关掉
    style = "dracula" # 推荐 dracula 或 monokai，背景比较深，适合这种风格
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]

[mediaTypes]
  [mediaTypes.'font/woff']
    suffixes = ['woff']
  [mediaTypes.'font/woff2']
    suffixes = ['woff2']
